name: flucidos-bootstrap
min-version: 2.0

element-path: elements

aliases:
  github: https://github.com/
  gitlab: https://gitlab.com/
  gnu-ftp: https://ftpmirror.gnu.org/
  gnu-git: https://git.savannah.gnu.org/git/
  gnome-git: https://gitlab.gnome.org/
  gnome-ftp: https://ftp.gnome.org/pub/GNOME/
  fdo: https://gitlab.freedesktop.org/
  fdo-ftp: https://www.freedesktop.org/software/
  sourceware: https://sourceware.org/git/
  sourceware-ftp: https://sourceware.org/pub/
  kernel: https://git.kernel.org/pub/scm/
  gnupg: https://dev.gnupg.org/source/
  videolan: https://code.videolan.org/videolan/
  xiph: https://gitlab.xiph.org/xiph/
  chromium: https://chromium.googlesource.com/
  sourceforge: https://sourceforge.net/projects/
  sourceforge-git: https://git.code.sf.net/p/
  webkitgtk: https://webkitgtk.org/releases/
  purism: https://source.puri.sm/
  libburnia: https://dev.lovelyhq.com/libburnia/
  google: https://dl.google.com/
  efifs: https://github.com/pbatard/efifs/releases/download/v1.8/
  netfilter: https://git.netfilter.org/
  ghostscript: https://git.ghostscript.com/
  nvidia: https://download.nvidia.com/
  w1fi: https://w1.fi/
  pypi: https://files.pythonhosted.org/packages/
  cpan: https://cpan.metacpan.org/
  cargo: https://static.crates.io/crates
  kitware: https://gitlab.kitware.com/
  coreboot: https://review.coreboot.org/
  debian: https://salsa.debian.org/
  pagure: https://pagure.io/
  poettering: https://git.0pointer.net/
  hadrons: https://git.hadrons.org/git/
  bitmath: https://bitmath.org/git/
  nettle: https://git.lysator.liu.se/nettle/
  openldap: https://git.openldap.org/
  linuxtv: https://git.linuxtv.org/
  tukaani: https://git.tukaani.org/
  ozlabs: https://git.ozlabs.org/
  libssh: https://git.libssh.org/projects/
  libreoffice: https://git.libreoffice.org/
  intra2net: https://www.intra2net.com/en/developer/
  rust: https://static.rust-lang.org/dist/
  https_files: https://

plugins:
  - origin: pip
    package-name: buildstream-plugins
    elements:
      - autotools
      - make
    sources:
      - git
  - origin: local
    path: plugins
    elements:
      - gnu

variables:
  target_arch: "x86_64"
  flucidos-target: "%{target_arch}-flucidos-linux-gnu"
  sysroot: "/sysroot"
  tools: "/tools"

elements: 
  autotools:
    variables:
      make-args: "-j %{max-jobs}"
    make:
      variables:
        make-args: "-j %{max-jobs}"
