# FlucidOS System Bootstrap
# carbonOS layout + GHA adaptations:
#   - custom bootstrap triplet
#   - github: alias for pkg-src tarballs
#   - import-fdo includes FDO bootstrap-import (host gcc on isolated GHA runners)

name: flucidOS-bootstrap
min-version: 2.0
element-path: elements
ref-storage: project.refs

fatal-warnings:
- overlaps
- ref-not-in-track
- unaliased-url

aliases:
  github: https://github.com/
  gitlab: https://gitlab.com/
  kernel: https://git.kernel.org/pub/scm/
  gnu-ftp: https://ftpmirror.gnu.org/gnu/
  sourceware: https://sourceware.org/git/
  kitware: https://gitlab.kitware.com/
  tukaani: https://git.tukaani.org/
  pypi: https://files.pythonhosted.org/packages/

variables:
  prefix: /tools
  sysconfdir: "%{prefix}/etc"
  localstatedir: "%{prefix}/var"
  sbindir: "%{bindir}"

  bootstrap-triplet: x86_64-flucidOS-linux-gnu
  bootstrap-sysroot: /sysroot

  strip-binaries: ""

elements:
  autotools:
    variables:
      build-dir: "."
      conf-root: "%{build-root}"
      configure: mkdir -p "%{build-dir}"; cd "%{build-dir}" && %{conf-cmd} %{conf-args}
      make: make -C "%{build-dir}" %{make-args}
      make-install: make -C "%{build-dir}" -j1 %{make-install-args}
      remove-libtool-modules: true
      remove-libtool-libraries: true

sources:
  git:
    config:
      track: master
  git_tag:
    config:
      track-tags: True
      track: master

environment:
  TERM: xterm-256color
  PATH: "%{bindir}:/usr/bin"
  PYTHONHASHSEED: 0

shell:
  command: ["bash", "--noprofile", "--norc", "-i"]
  host-files:
  - /sys
  - /etc/passwd
  - /etc/group
  - /etc/resolv.conf

plugins:
- origin: junction
  junction: bst-plugins.bst
  elements:
  - autotools
  - cmake
  - make
  sources:
  - git
  - patch
- origin: junction
  junction: bst-plugins-experimental.bst
  sources:
  - git_tag

junctions:
  internal:
  - freedesktop-sdk.bst
  - bst-plugins.bst
  - bst-plugins-experimental.bst
