name: Bootstrap flucidOS Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-Bootstrap:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Fix Bubblewrap Permissions
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Install BuildStream
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv bubblewrap git tar zstd curl
          python3 -m venv .venv
          .venv/bin/pip install --upgrade pip
          # Added dulwich to satisfy git_repo plugin requirements
          .venv/bin/pip install "buildstream==2.8.0" dulwich
          .venv/bin/bst --version

      - name: Configure BuildStream Cache Rules
        run: |
          mkdir -p ~/.config
          cat <<EOF > ~/.config/buildstream.conf
          cache:
            quota: infinity
            pull-buildtrees: False
            cache-buildtrees: never
          EOF

      - name: Install ORAS & Login
        run: |
          curl -LO "https://github.com/oras-project/oras/releases/download/v1.2.0/oras_1.2.0_linux_amd64.tar.gz"
          mkdir -p oras-install
          tar -zxf oras_1.2.0_linux_amd64.tar.gz -C oras-install
          sudo mv oras-install/oras /usr/local/bin/
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Restore Cache from GHCR
        run: |
          # Convert repository name to strict lowercase for OCI compliance
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          oras pull ghcr.io/${REPO_LOWER}/bst-cache:latest || echo "No existing cache found."
          
          if [ -f bst-cache.tar.zst ]; then
            tar -I zstd -xf bst-cache.tar.zst -C ~/
          fi

      - name: Track Sources
        run: .venv/bin/bst source track all.bst

      - name: Build flucidOS-bootstrap
        run: .venv/bin/bst build all.bst

      - name: Save Cache to GHCR
        if: always()
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          if [ -d ~/.cache/buildstream ]; then
            tar -I zstd -cf bst-cache.tar.zst -C ~/ .cache/buildstream
            oras push ghcr.io/${REPO_LOWER}/bst-cache:latest bst-cache.tar.zst
          fi
