name: Bootstrap flucidOS Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-os:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Fix Bubblewrap Permissions
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Install BuildStream
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv bubblewrap git
          python3 -m venv .venv
          .venv/bin/pip install buildstream

      - name: Configure BuildStream Cache Rules
        run: |
          mkdir -p ~/.config
          cat <<EOF > ~/.config/buildstream.conf
          cache:
            quota: system
            pull-buildtrees: False
            cache-buildtrees: never
          EOF

      - name: Restore BuildStream Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/buildstream
          key: bst-cache-${{ github.sha }}
          restore-keys: |
            bst-cache-

      - name: Track Sources
        run: .venv/bin/bst source track all.bst

      - name: Build flucidOS
        run: .venv/bin/bst build all.bst
